name: Terraform
on:
  push:
    branches:
      - main
jobs:
  Apply-Terraform-Main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: check
        run: |
          cat ${{ secrets.AWS_ACCESS_KEY_ID }}
          cat ${{ secrets.AWS_ACCESS_KEY_SECRET }}

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: eu-west-3

      - name: mailing-signature s3 upload
        run: |
          aws s3 sync ./assets s3://mailingsignature/Images

